export const FRONTEND_ASSET_MANIFEST = Object.freeze({
  entry: "/index.html",
  outputDirectory: "frontend/dist",
  spaRoutes: Object.freeze([
    "/",
    "/submit",
    "/knowledge",
    "/search",
    "/agent",
    "/my-submissions",
    "/admin",
    "/admin/submissions",
    "/admin/assets",
    "/admin/members",
    "/admin/roles",
    "/admin/menus",
    "/admin/spaces",
    "/admin/audit",
    "/admin/analytics",
  ]),
});
