import type { FrontendLocale, LocaleRuntime } from "../../lib/i18n";

const en = {
  BRAND: "Personal Workbench",
  HERO_TITLE: "Turn your knowledge into everyday action.",
  HERO_DESCRIPTION: "A personal workbench built around your AI knowledge base. Collect sources, ask questions, and connect knowledge to tasks and boards.",
  START: "Try the knowledge journey",
  EXPLORE: "Explore the workbench",
  LOGIN: "Log in to your workbench",
  INVITE_ONLY: "Access is invitation-only. Log in with an approved GitHub account.",
  DEMO_BADGE: "Example demo · Does not read your personal data",
  DEMO_DESCRIPTION: "All documents, answers, citations, tasks and messages here are handwritten fictional examples.",
  FLOW_TITLE: "From collected material to your next action",
  FLOW_DESCRIPTION: "Keep sources, read and organize knowledge, check cited answers, then manually create and track your next task.",
  PRIVACY_TITLE: "Your data stays outside this demo",
  PRIVACY_DESCRIPTION: "This demo does not read your personal data, upload files or send AI requests. Demo actions stay in memory and reset on refresh; they do not write to your workspace.",
  FOOTER_CTA: "Ready to connect your knowledge and action?",

  GUIDE_LABEL: "Knowledge journey progress",
  GUIDE_HINT: "A short, self-paced tour. Continue when you are ready, or explore any feature.",
  NEXT: "Next step",
  REPLAY: "Replay the demo",
  CLOSE_PANEL: "Close demo panel",
  BACK_TO_ANSWER: "Back to the example answer",
  OPEN_SOURCE: "Read source document",
  SOURCE_LABEL: "Source",
  PARAGRAPH_LABEL: "Source paragraph",
  CITATIONS_LABEL: "Answer sources",
  QUESTION_LABEL: "Example question",
  ANSWER_LABEL: "Example answer",
  HOTSPOTS_LABEL: "Workbench features",
  STEP_OVERVIEW: "Overview",
  STEP_CAPTURE: "Collect",
  STEP_LIBRARY: "Read and organize",
  STEP_ANSWER: "Ask with sources",
  STEP_ACTION: "Manage action",
  STEP_COMPLETE: "Journey complete",

  CAPTURE_TITLE: "Keep material and its source together",
  CAPTURE_DESCRIPTION: "Choose a prepared project document to try collecting it. This changes only the demo; no file is uploaded.",
  CAPTURE_SELECT: "Collect example material",
  CAPTURE_PENDING: "Example material not yet collected",
  CAPTURE_DONE: "Example material collected locally",
  CAPTURE_GATE: "Collect the example material before continuing.",
  LIBRARY_TITLE: "Read, review and build your knowledge library",
  LIBRARY_DESCRIPTION: "Read the two example documents and their summary. In the workbench, material is reviewed before publication; this demo does not publish anything.",
  LIBRARY_SUMMARY: "Keep original sources, summarize what you read, and use a weekly review to choose a next action.",
  LIBRARY_REVIEW: "Review the summary and source context before publication.",
  LIBRARY_PUBLISHED: "Published example · Read-only demo",
  ANSWER_TITLE: "Trace an answer back to its sources",
  ANSWER_DESCRIPTION: "Choose the fixed example question to read a prepared answer. No live AI request is sent.",
  ANSWER_SHOW: "Show the example answer",
  ANSWER_CITATION_HINT: "Select a citation to read the original paragraph in context.",
  ACTION_TITLE: "Decide the next step yourself",
  ACTION_DESCRIPTION: "This prepared task illustrates a to-do you would create manually after reading. Answers do not automatically create or execute tasks. Moving this card changes only the local demo.",
  ACTION_COMPLETE: "Demo: move to Done",
  ACTION_TODO: "To do",
  ACTION_DONE: "Done in this demo",
  ACTION_GATE: "Move the example task to Done before continuing.",
  TASK_LABEL: "Example task",
  BOARD_LABEL: "Example task board",
  UPDATES_TITLE: "Keep updates in context",
  UPDATES_DESCRIPTION: "These prepared notification and discussion examples belong to the same task. They are not live messages or general direct messaging.",
  UPDATES_NOTIFICATION: "Task notification example",
  UPDATES_DISCUSSION: "Task discussion example",
  COMPLETE_TITLE: "Knowledge connected to a next action",
  COMPLETE_DESCRIPTION: "This demo illustrates collecting material, reading sources, checking cited answers and manually tracking a task.",

  SCENE_LABEL: "Interactive knowledge workbench",
  SCENE_POSTER_ALT: "A miniature knowledge studio with a collection tray, document shelves, answer desk, task board and notification corner.",
  SCENE_IDLE: "The static preview is ready. Load 3D when you choose.",
  SCENE_LOADING: "Loading the 3D workbench. You can still explore the demo or log in.",
  SCENE_READY: "The 3D workbench is ready. Select a feature to explore.",
  SCENE_STATIC: "Static mode. All demo features and login remain available.",
  SCENE_REDUCED_MOTION: "A static preview is shown for your reduced-motion preference. You can choose to load 3D.",
  SCENE_SAVE_DATA: "A static preview is shown to respect your data-saving preference. Load 3D only if you choose.",
  SCENE_ERROR: "The 3D scene could not load. Use the static demo or retry when you are ready.",
  SCENE_UNAVAILABLE: "3D is unavailable in this browser. The static demo and login are still available.",
  SCENE_TIMEOUT: "3D loading stopped after 8 seconds. Continue with the static demo or retry manually.",
  SCENE_CONTEXT_LOST: "The 3D view was interrupted. The static demo is available; retry to reload 3D.",
  SCENE_MISSING_NODES: "The 3D scene is incomplete. Continue with the static demo or retry loading it.",
  SCENE_LOAD: "Load 3D",
  SCENE_RETRY: "Retry 3D loading",
  SCENE_STATIC_MODE: "Use static mode",
  SCENE_PAUSE: "Pause animation",
  SCENE_RESUME: "Resume animation",
  SCENE_PAUSED: "Animation paused. You can still use every demo control.",
  SWITCH_LANGUAGE: "Change language",
  SWITCH_THEME: "Change theme",
} as const;

export type LandingCopyKey = keyof typeof en;

const catalogs: Record<FrontendLocale, Record<LandingCopyKey, string>> = {
  en,
  "zh-CN": {
    BRAND: "个人工作台",
    HERO_TITLE: "让你的知识，成为每天的行动力。",
    HERO_DESCRIPTION: "以 AI 知识库为核心的个人工作台。收集资料、整理知识、追问答案，用任务与看板连接知识和行动。",
    START: "体验知识之旅",
    EXPLORE: "探索工作台",
    LOGIN: "登录工作台",
    INVITE_ONLY: "工作台采用邀请制，请使用已获准的 GitHub 账号登录。",
    DEMO_BADGE: "示例演示 · 不读取你的个人数据",
    DEMO_DESCRIPTION: "这里的资料、回答、引用、任务及消息均为人工编写的虚构样例。",
    FLOW_TITLE: "从收集资料，到下一步行动",
    FLOW_DESCRIPTION: "保留来源，阅读整理知识，核对回答引用，再人工创建并跟进下一步任务。",
    PRIVACY_TITLE: "你的数据不参与这场演示",
    PRIVACY_DESCRIPTION: "演示不读取个人数据、不上传文件，也不发送 AI 请求。演示操作只保留在内存中，刷新即重置，不写入你的工作台。",
    FOOTER_CTA: "准备好连接你的知识与行动了吗？",

    GUIDE_LABEL: "知识之旅进度",
    GUIDE_HINT: "按自己的节奏体验这段简短流程。准备好后再继续，也可随时探索任意功能。",
    NEXT: "下一步",
    REPLAY: "重新体验",
    CLOSE_PANEL: "关闭演示面板",
    BACK_TO_ANSWER: "返回示例回答",
    OPEN_SOURCE: "阅读来源正文",
    SOURCE_LABEL: "来源",
    PARAGRAPH_LABEL: "来源段落",
    CITATIONS_LABEL: "回答来源",
    QUESTION_LABEL: "示例问题",
    ANSWER_LABEL: "示例回答",
    HOTSPOTS_LABEL: "工作台功能",
    STEP_OVERVIEW: "概览",
    STEP_CAPTURE: "收集资料",
    STEP_LIBRARY: "阅读整理",
    STEP_ANSWER: "基于来源提问",
    STEP_ACTION: "管理行动",
    STEP_COMPLETE: "体验完成",

    CAPTURE_TITLE: "让资料和来源一起留下",
    CAPTURE_DESCRIPTION: "选择预置的项目资料卡，体验收集过程。这里只改变演示状态，不会上传文件。",
    CAPTURE_SELECT: "收集示例资料",
    CAPTURE_PENDING: "尚未收集示例资料",
    CAPTURE_DONE: "已在本地收集示例资料",
    CAPTURE_GATE: "请先收集示例资料，再继续下一步。",
    LIBRARY_TITLE: "阅读、审核，形成知识库",
    LIBRARY_DESCRIPTION: "阅读两篇示例正文及其摘要。在工作台中，资料经过审核后再发布；本演示不会实际发布内容。",
    LIBRARY_SUMMARY: "保留原始来源，归纳阅读要点，再通过每周回顾确定下一步行动。",
    LIBRARY_REVIEW: "发布前核对摘要与来源上下文。",
    LIBRARY_PUBLISHED: "已发布样例 · 只读演示",
    ANSWER_TITLE: "沿着引用，核对回答的依据",
    ANSWER_DESCRIPTION: "选择固定示例问题，查看预先编写的回答。这里不会发送真实 AI 请求。",
    ANSWER_SHOW: "查看示例回答",
    ANSWER_CITATION_HINT: "选择一条引用，阅读对应原文段落及其上下文。",
    ACTION_TITLE: "由你决定下一步行动",
    ACTION_DESCRIPTION: "这张预置任务卡展示阅读后可由你人工创建的待办。回答不会自动创建或执行任务；移动卡片只改变本地演示状态。",
    ACTION_COMPLETE: "演示移至完成",
    ACTION_TODO: "待办",
    ACTION_DONE: "演示中已完成",
    ACTION_GATE: "请先将示例任务移至完成，再继续下一步。",
    TASK_LABEL: "示例任务",
    BOARD_LABEL: "示例任务看板",
    UPDATES_TITLE: "让通知和讨论留在上下文中",
    UPDATES_DESCRIPTION: "这些预置通知和讨论均围绕同一张示例任务卡，不是真实消息，也不是通用私信。",
    UPDATES_NOTIFICATION: "任务通知示例",
    UPDATES_DISCUSSION: "任务讨论示例",
    COMPLETE_TITLE: "从知识，走到下一步行动",
    COMPLETE_DESCRIPTION: "本演示展示了收集资料、阅读来源、核对回答引用和手动跟进任务的流程。",

    SCENE_LABEL: "交互式知识工作台",
    SCENE_POSTER_ALT: "一间微缩知识工作室，包含收集托盘、资料书架、问答桌、任务看板和通知角。",
    SCENE_IDLE: "静态预览已就绪，可由你选择加载 3D。",
    SCENE_LOADING: "正在加载 3D 工作台，你仍可探索演示或登录。",
    SCENE_READY: "3D 工作台已就绪，选择一个功能开始探索。",
    SCENE_STATIC: "当前为静态模式，所有演示功能和登录入口仍可使用。",
    SCENE_REDUCED_MOTION: "已根据你的减少动态效果偏好显示静态预览，你仍可主动加载 3D。",
    SCENE_SAVE_DATA: "已根据你的数据节省偏好显示静态预览，仅在你选择后加载 3D。",
    SCENE_ERROR: "3D 场景加载失败，可以使用静态演示，或准备好后重试。",
    SCENE_UNAVAILABLE: "当前浏览器无法使用 3D，静态演示和登录入口仍可使用。",
    SCENE_TIMEOUT: "3D 加载超过 8 秒，已停止尝试。可以继续静态演示，或手动重试。",
    SCENE_CONTEXT_LOST: "3D 画面已中断，静态演示仍可使用；可重试以重新加载 3D。",
    SCENE_MISSING_NODES: "3D 场景内容不完整，可以继续静态演示，或重新加载。",
    SCENE_LOAD: "加载 3D",
    SCENE_RETRY: "重试加载 3D",
    SCENE_STATIC_MODE: "使用静态模式",
    SCENE_PAUSE: "暂停动画",
    SCENE_RESUME: "继续动画",
    SCENE_PAUSED: "动画已暂停，所有演示操作仍可使用。",
    SWITCH_LANGUAGE: "切换语言",
    SWITCH_THEME: "切换主题",
  },
};

// The public key inventory lets focused tests cover this local catalog in full.
export const LANDING_COPY_KEYS: readonly LandingCopyKey[] = Object.freeze(Object.keys(en) as LandingCopyKey[]);

export function landingText(locale: LocaleRuntime, key: LandingCopyKey): string {
  return catalogs[locale.locale][key];
}
