import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent } from "../../components/ui/card";
import { PageState } from "../../components/ui/page-state";
import { frontendText, type LocaleRuntime } from "../../lib/i18n";
import type { AdminDuplicateCandidate, DuplicateDecision } from "../../lib/admin-duplicates-data";
import type { AdminDuplicatePageResult } from "../../lib/admin-duplicates-data";
import { DataPagination } from "../../components/data-pagination";
import type { SupportedPageSize } from "../../lib/numbered-page";

export function DuplicateQueuePage({ state, locale, pendingId, pending, localError, onDecision, onPageChange, onPageSizeChange }: { state: { kind: "loading" } | { kind: "ready"; data: AdminDuplicatePageResult } | { kind: "error"; message: string }; locale?: LocaleRuntime; pendingId?: string | null; pending?: boolean; localError?: string; onDecision?: (id: string, decision: DuplicateDecision) => void; onPageChange?: (page: number) => void; onPageSizeChange?: (size: SupportedPageSize) => void }) {
  if (state.kind === "loading") return <PageState kind="loading" title={frontendText(locale, "APP_LOADING_TITLE")} />;
  if (state.kind === "error") return <PageState kind="error" title={state.message || frontendText(locale, "COMMON_UNABLE_TO_LOAD")} />;
  return <section className="space-y-5"><div><h1 className="text-2xl font-semibold">{frontendText(locale, "ADMIN_DUPLICATE_TITLE")}</h1><p className="mt-1 text-sm text-muted-foreground">{frontendText(locale, "ADMIN_DUPLICATE_DESCRIPTION")}</p></div>{localError && <p role="alert" className="text-sm text-destructive">{localError}</p>}{state.data.items.length ? state.data.items.map((item: AdminDuplicateCandidate) => { const itemPending = pendingId === item.submissionId; const target = item.submissionTitle.trim() || item.submissionId; return <Card key={item.submissionId}><CardContent className="space-y-4 p-4"><div className="flex items-start justify-between gap-4"><div><h2 className="font-medium">{item.submissionTitle}</h2><p className="mt-1 text-sm text-muted-foreground">{frontendText(locale, "ADMIN_DUPLICATE_CANONICAL")}: {item.canonicalTitle}</p></div><Badge variant="warning">{frontendText(locale, "ADMIN_DUPLICATE_PENDING")}</Badge></div><div className="flex flex-wrap gap-2"><Button aria-label={`${frontendText(locale, "ADMIN_DUPLICATE_ASSOCIATE")} ${target}`} size="sm" disabled={itemPending} onClick={() => onDecision?.(item.submissionId, "associate")}>{frontendText(locale, "ADMIN_DUPLICATE_ASSOCIATE")}</Button><Button aria-label={`${frontendText(locale, "ADMIN_DUPLICATE_KEEP_SEPARATE")} ${target}`} size="sm" variant="outline" disabled={itemPending} onClick={() => onDecision?.(item.submissionId, "keep_separate")}>{frontendText(locale, "ADMIN_DUPLICATE_KEEP_SEPARATE")}</Button><Button aria-label={`${frontendText(locale, "ADMIN_DUPLICATE_REJECT")} ${target}`} size="sm" variant="destructive" disabled={itemPending} onClick={() => onDecision?.(item.submissionId, "reject")}>{frontendText(locale, "ADMIN_DUPLICATE_REJECT")}</Button></div></CardContent></Card>; }) : <PageState kind="empty" title={frontendText(locale, "ADMIN_DUPLICATE_EMPTY")} description={frontendText(locale, "ADMIN_DUPLICATE_DESCRIPTION")} />}<DataPagination {...state.data.pagination} pending={pending} onPageChange={(page) => onPageChange?.(page)} onPageSizeChange={(size) => onPageSizeChange?.(size)} /></section>;
}
