import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent } from "../../components/ui/card";
import { PageState } from "../../components/ui/page-state";
import { frontendText, type LocaleRuntime } from "../../lib/i18n";
import type { AdminDuplicateCandidate, DuplicateDecision } from "../../lib/admin-duplicates-data";

export function DuplicateQueuePage({ state, locale, pendingId, onDecision, onLoadMore }: { state: { kind: "loading" } | { kind: "ready"; items: readonly AdminDuplicateCandidate[]; nextCursor: string | null; pending?: boolean; error?: string } | { kind: "error"; message: string }; locale?: LocaleRuntime; pendingId?: string | null; onDecision?: (id: string, decision: DuplicateDecision) => void; onLoadMore?: () => void }) {
  if (state.kind === "loading") return <PageState kind="loading" title={frontendText(locale, "APP_LOADING_TITLE")} />;
  if (state.kind === "error") return <PageState kind="error" title={state.message || frontendText(locale, "COMMON_UNABLE_TO_LOAD")} />;
  if (!state.items.length) return <PageState kind="empty" title={frontendText(locale, "ADMIN_DUPLICATE_EMPTY")} description={frontendText(locale, "ADMIN_DUPLICATE_DESCRIPTION")} />;
  return <section className="space-y-5"><div><h1 className="text-2xl font-semibold">{frontendText(locale, "ADMIN_DUPLICATE_TITLE")}</h1><p className="mt-1 text-sm text-muted-foreground">{frontendText(locale, "ADMIN_DUPLICATE_DESCRIPTION")}</p></div>{state.error && <p role="alert" className="text-sm text-destructive">{state.error}</p>}{state.items.map((item) => { const pending = pendingId === item.submissionId; return <Card key={item.submissionId}><CardContent className="space-y-4 p-4"><div className="flex items-start justify-between gap-4"><div><h2 className="font-medium">{item.submissionTitle}</h2><p className="mt-1 text-sm text-muted-foreground">{frontendText(locale, "ADMIN_DUPLICATE_CANONICAL")}: {item.canonicalTitle}</p></div><Badge variant="warning">{frontendText(locale, "ADMIN_DUPLICATE_PENDING")}</Badge></div><div className="flex flex-wrap gap-2"><Button size="sm" disabled={pending} onClick={() => onDecision?.(item.submissionId, "associate")}>{frontendText(locale, "ADMIN_DUPLICATE_ASSOCIATE")}</Button><Button size="sm" variant="outline" disabled={pending} onClick={() => onDecision?.(item.submissionId, "keep_separate")}>{frontendText(locale, "ADMIN_DUPLICATE_KEEP_SEPARATE")}</Button><Button size="sm" variant="destructive" disabled={pending} onClick={() => onDecision?.(item.submissionId, "reject")}>{frontendText(locale, "ADMIN_DUPLICATE_REJECT")}</Button></div></CardContent></Card>; })}{state.nextCursor && <Button variant="outline" disabled={state.pending || Boolean(pendingId)} onClick={onLoadMore}>{frontendText(locale, "ADMIN_LOAD_MORE")}</Button>}</section>;
}
