import { DataPagination } from "../../components/data-pagination";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent } from "../../components/ui/card";
import { PageState } from "../../components/ui/page-state";
import { frontendText, type LocaleRuntime } from "../../lib/i18n";
import type { FrontendPageMetadata, SupportedPageSize } from "../../lib/numbered-page";

export function MembersPage({ members, pagination, status = "", pendingIds = [], loading = false, pending = false, error, pageError, actionError, onStatusFilterChange, onPageChange, onPageSizeChange, onStatusChange, locale }: { members: readonly { id: string; email?: string; role?: string; status?: string }[]; pagination?: FrontendPageMetadata; status?: "" | "active" | "disabled"; pendingIds?: readonly string[]; loading?: boolean; pending?: boolean; error?: string; pageError?: string; actionError?: string; onStatusFilterChange?: (status: "" | "active" | "disabled") => void; onPageChange?: (page: number) => void; onPageSizeChange?: (size: SupportedPageSize) => void; onStatusChange?: (id: string, status: "active" | "disabled") => void; locale?: LocaleRuntime }) {
  if (loading) return <PageState kind="loading" title={frontendText(locale, "APP_LOADING_TITLE")} />;
  if (error) return <PageState kind="error" title={error} description={frontendText(locale, "COMMON_UNABLE_TO_LOAD")} />;
  return <section className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">{frontendText(locale, "ADMIN_MEMBERS_TITLE")}</h1><p className="mt-1 text-sm text-muted-foreground">{frontendText(locale, "ADMIN_MEMBERS_DESCRIPTION")}</p></div><label className="text-sm text-muted-foreground">Status <select aria-label="Member status" className="ml-2 h-9 rounded-md border bg-background px-2" disabled={pending} value={status} onChange={(event) => onStatusFilterChange?.(event.target.value as "" | "active" | "disabled")}><option value="">All</option><option value="active">Active</option><option value="disabled">Disabled</option></select></label></div>
    {(actionError || pageError) && <p role="alert" className="text-sm text-destructive">{actionError || pageError}</p>}
    {members.length ? <div className="space-y-3">{members.map((member) => { const disabled = member.status === "disabled"; const itemPending = pendingIds.includes(member.id); const actionLabel = disabled ? frontendText(locale, "ADMIN_ENABLE") : frontendText(locale, "ADMIN_DISABLE"); const target = member.email || member.id; return <Card key={member.id}><CardContent className="flex items-center justify-between gap-4 p-4"><div><p className="font-medium">{member.email || frontendText(locale, "ADMIN_EMAIL_UNAVAILABLE")}</p><p className="mt-1 text-xs text-muted-foreground">{member.role || frontendText(locale, "ADMIN_ROLE_UNAVAILABLE")}</p></div><div className="flex items-center gap-3"><Badge variant={disabled ? "destructive" : "success"}>{disabled ? frontendText(locale, "ADMIN_DISABLED") : frontendText(locale, "ADMIN_ACTIVE")}</Badge><Button aria-label={`${actionLabel} ${target}`} size="sm" variant="outline" disabled={itemPending} onClick={() => onStatusChange?.(member.id, disabled ? "active" : "disabled")}>{actionLabel}</Button></div></CardContent></Card>; })}</div> : <PageState kind="empty" title={frontendText(locale, "ADMIN_MEMBERS_EMPTY")} description={frontendText(locale, "ADMIN_MEMBERS_DESCRIPTION")} />}
    {pagination && <DataPagination {...pagination} locale={locale} pending={pending} onPageChange={(page) => onPageChange?.(page)} onPageSizeChange={(size) => onPageSizeChange?.(size)} />}
  </section>;
}
