import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "../../components/ui/card";
import { Button } from "../../components/ui/button";
import { Badge } from "../../components/ui/badge";
import { PageState } from "../../components/ui/page-state";
import { frontendText, type LocaleRuntime } from "../../lib/i18n";
import type { AdminMenu } from "../../lib/admin-menus-data";

export function AdminMenusPage({ state, locale, onUpdate, onDelete, pendingId, error }: { state: { kind: "loading" } | { kind: "error"; message?: string } | { kind: "ready"; menus: readonly AdminMenu[] }; locale?: LocaleRuntime; onUpdate?: (menu: AdminMenu, input: { position?: number; status?: "active" | "disabled"; visible?: boolean }) => void; onDelete?: (menu: AdminMenu) => void; pendingId?: string | null; error?: string | null }) {
  if (state.kind === "loading") return <PageState kind="loading" title={frontendText(locale, "APP_LOADING_TITLE")} />;
  if (state.kind === "error") return <PageState kind="error" title={state.message || frontendText(locale, "ADMIN_MENUS_UNAVAILABLE")} />;
  if (!state.menus.length) return <PageState kind="empty" title={frontendText(locale, "ADMIN_MENUS_EMPTY")} description={frontendText(locale, "ADMIN_MENUS_DESCRIPTION")} />;
  return <section className="space-y-6"><div><p className="text-sm font-medium text-primary">{frontendText(locale, "ADMIN_EYEBROW")}</p><h1 className="mt-2 text-2xl font-semibold">{frontendText(locale, "ADMIN_MENUS_TITLE")}</h1><p className="mt-1 text-sm text-muted-foreground">{frontendText(locale, "ADMIN_MENUS_DESCRIPTION")}</p></div><Card><CardHeader><CardTitle>{frontendText(locale, "ADMIN_MENUS_TREE")}</CardTitle></CardHeader><CardContent>{error && <p role="alert" className="mb-4 text-sm text-destructive">{error}</p>}<div className="space-y-2">{state.menus.map((menu) => <MenuNode key={menu.id} menu={menu} depth={0} locale={locale} onUpdate={onUpdate} onDelete={onDelete} pendingId={pendingId} />)}</div></CardContent></Card></section>;
}

function MenuNode({ menu, depth, locale, onUpdate, onDelete, pendingId }: { menu: AdminMenu; depth: number; locale?: LocaleRuntime; onUpdate?: (menu: AdminMenu, input: { position?: number; status?: "active" | "disabled"; visible?: boolean }) => void; onDelete?: (menu: AdminMenu) => void; pendingId?: string | null }) {
  const [position, setPosition] = useState(menu.position);
  const busy = pendingId === menu.id;
  return <div className="space-y-2" style={{ marginLeft: `${Math.min(depth, 4) * 1.25}rem` }}><div className="flex flex-wrap items-center gap-3 rounded-md border px-3 py-2"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{menu.labelKey}</p><p className="truncate text-xs text-muted-foreground">{menu.path || menu.key} · {menu.requiredBits}</p></div>{menu.isSystem && <Badge variant="outline">{frontendText(locale, "ADMIN_MENUS_SYSTEM")}</Badge>}<Badge variant={menu.status === "active" ? "secondary" : "outline"}>{menu.status === "active" ? frontendText(locale, "ADMIN_MENUS_ACTIVE") : frontendText(locale, "ADMIN_MENUS_DISABLED")}</Badge><label className="flex items-center gap-2 text-xs"><span className="sr-only">{frontendText(locale, "ADMIN_MENUS_POSITION")}</span><input className="h-8 w-16 rounded-md border bg-background px-2 text-sm" type="number" min={0} value={position} disabled={menu.isSystem || busy} onChange={(event) => setPosition(Number(event.target.value))} /></label><Button type="button" size="sm" variant="outline" disabled={menu.isSystem || busy || position === menu.position} onClick={() => onUpdate?.(menu, { position })}>{frontendText(locale, "ADMIN_MENUS_SAVE")}</Button><Button type="button" size="sm" variant="ghost" disabled={menu.isSystem || busy} onClick={() => onUpdate?.(menu, { status: menu.status === "active" ? "disabled" : "active" })}>{menu.status === "active" ? frontendText(locale, "ADMIN_MENUS_DISABLE") : frontendText(locale, "ADMIN_MENUS_ENABLE")}</Button>{!menu.isSystem && menu.children.length === 0 && <Button type="button" size="sm" variant="ghost" disabled={busy} onClick={() => onDelete?.(menu)}>{frontendText(locale, "ADMIN_MENUS_DELETE")}</Button>}</div>{menu.children.map((child) => <MenuNode key={child.id} menu={child} depth={depth + 1} locale={locale} onUpdate={onUpdate} onDelete={onDelete} pendingId={pendingId} />)}</div>;
}
