import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent } from "../../components/ui/card";
import { Skeleton } from "../../components/ui/skeleton";
import { PageState } from "../../components/ui/page-state";
import { frontendText, type LocaleRuntime } from "../../lib/i18n";
import { DataPagination } from "../../components/data-pagination";
import type { ReviewQueuePageResult } from "../../lib/admin-review-data";
import type { SupportedPageSize } from "../../lib/numbered-page";

export function ReviewQueuePage({ state, onReview, pendingId, actionError, localError, pending, onPageChange, onPageSizeChange, locale }: { state: { kind: "loading" } | { kind: "ready"; data: ReviewQueuePageResult } | { kind: "error"; message: string }; onReview?: (id: string, action: "publish" | "reject" | "request_changes") => void; pendingId?: string | null; actionError?: string; localError?: string; pending?: boolean; onPageChange?: (page: number) => void; onPageSizeChange?: (size: SupportedPageSize) => void; locale?: LocaleRuntime }) {
  if (state.kind === "loading") return <div aria-busy="true"><Skeleton className="h-24" /></div>;
  if (state.kind === "error") return <PageState kind="error" title={state.message || frontendText(locale, "COMMON_UNABLE_TO_LOAD")} />;
  return <section className="space-y-5"><div><h1 className="text-2xl font-semibold">{frontendText(locale, "ADMIN_REVIEW_QUEUE_TITLE")}</h1><p className="mt-1 text-sm text-muted-foreground">{frontendText(locale, "ADMIN_REVIEW_QUEUE_DESCRIPTION")}</p></div>{(actionError || localError) && <p role="alert" className="text-sm text-destructive">{actionError || localError}</p>}{state.data.items.length ? state.data.items.map((item) => { const itemPending = pendingId === item.id; const target = item.title?.trim() || item.id; return <Card key={item.id}><CardContent className="space-y-4 p-4"><div className="flex items-start justify-between gap-4"><div><h2 className="font-medium"><a href={`/admin/submissions/${encodeURIComponent(item.id)}`} className="hover:underline">{item.title?.trim() || frontendText(locale, "ADMIN_REVIEW_UNTITLED")}</a></h2><p className="mt-1 text-xs text-muted-foreground">{item.submitter || frontendText(locale, "ADMIN_REVIEW_SUBMITTER_UNAVAILABLE")}</p></div><Badge variant="outline">{item.status || frontendText(locale, "ADMIN_REVIEW_STATUS_UNAVAILABLE")}</Badge></div><div className="flex flex-wrap gap-2"><Button aria-label={`${frontendText(locale, "ADMIN_REVIEW_PUBLISH")} ${target}`} size="sm" disabled={itemPending} onClick={() => onReview?.(item.id, "publish")}>{itemPending ? frontendText(locale, "ADMIN_REVIEW_ACTION_PENDING") : frontendText(locale, "ADMIN_REVIEW_PUBLISH")}</Button><Button aria-label={`${frontendText(locale, "ADMIN_REVIEW_REQUEST_CHANGES")} ${target}`} size="sm" variant="outline" disabled={itemPending} onClick={() => onReview?.(item.id, "request_changes")}>{frontendText(locale, "ADMIN_REVIEW_REQUEST_CHANGES")}</Button><Button aria-label={`${frontendText(locale, "ADMIN_REVIEW_REJECT")} ${target}`} size="sm" variant="destructive" disabled={itemPending} onClick={() => onReview?.(item.id, "reject")}>{frontendText(locale, "ADMIN_REVIEW_REJECT")}</Button></div></CardContent></Card>; }) : <PageState kind="empty" title={frontendText(locale, "ADMIN_REVIEW_EMPTY")} description={frontendText(locale, "ADMIN_REVIEW_QUEUE_DESCRIPTION")} />}<DataPagination {...state.data.pagination} pending={pending} onPageChange={(page) => onPageChange?.(page)} onPageSizeChange={(size) => onPageSizeChange?.(size)} /></section>;
}
