import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { PageState } from "../components/ui/page-state";
import { frontendText, type LocaleRuntime } from "../lib/i18n";

export type HomeState = { kind: "loading" } | { kind: "ready"; total: number; pending: number; published: number; recent?: readonly { id: string; title: string; summary?: string }[] } | { kind: "error"; message: string };

export function HomePage({ state, locale }: { state: HomeState; locale?: LocaleRuntime }) {
  if (state.kind === "loading") return <PageState kind="loading" title={frontendText(locale, "APP_LOADING_TITLE")} />;
  if (state.kind === "error") return <PageState kind="error" title={state.message || frontendText(locale, "COMMON_UNABLE_TO_LOAD")} />;
  return <section className="space-y-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">{frontendText(locale, "APP_BRAND_EYEBROW")}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{frontendText(locale, "HOME_TITLE")}</h1><p className="mt-2 max-w-2xl text-muted-foreground">{frontendText(locale, "HOME_DESCRIPTION")}</p></div><a href="/submit" className="inline-flex h-9 items-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground hover:bg-primary/90">{frontendText(locale, "HOME_QUICK_SUBMIT")}</a></div><div className="grid gap-4 md:grid-cols-3">{[[frontendText(locale, "HOME_TOTAL_SUBMISSIONS"), state.total], [frontendText(locale, "HOME_PENDING_REVIEW"), state.pending], [frontendText(locale, "HOME_PUBLISHED_KNOWLEDGE"), state.published]].map(([label, value]) => <Card key={label as string}><CardHeader><CardTitle className="text-sm font-medium text-muted-foreground">{label}</CardTitle></CardHeader><CardContent><p className="text-3xl font-semibold tabular-nums">{value}</p></CardContent></Card>)}</div><div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]"><Card><CardHeader><CardTitle>{frontendText(locale, "HOME_RECENT_TITLE")}</CardTitle></CardHeader><CardContent>{state.recent?.length ? <div className="divide-y">{state.recent.map((item) => <a key={item.id} href={`/knowledge/${encodeURIComponent(item.id)}`} className="block py-3 first:pt-0 last:pb-0 hover:text-primary"><p className="font-medium">{item.title || frontendText(locale, "KNOWLEDGE_UNTITLED")}</p>{item.summary && <p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{item.summary}</p>}</a>)}</div> : <p className="text-sm text-muted-foreground">{frontendText(locale, "HOME_RECENT_EMPTY")}</p>}</CardContent></Card><Card><CardHeader><CardTitle>{frontendText(locale, "HOME_QUICK_ACTIONS")}</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2 lg:grid-cols-1"><a href="/knowledge" className="rounded-md border px-3 py-2 text-sm hover:bg-accent">{frontendText(locale, "HOME_OPEN_KNOWLEDGE")}</a><a href="/search" className="rounded-md border px-3 py-2 text-sm hover:bg-accent">{frontendText(locale, "HOME_OPEN_SEARCH")}</a><a href="/agent" className="rounded-md border px-3 py-2 text-sm hover:bg-accent">{frontendText(locale, "HOME_OPEN_AGENT")}</a></CardContent></Card></div></section>;
}
