import { Button } from "../components/ui/button";
import { Card, CardContent } from "../components/ui/card";
import { PageState } from "../components/ui/page-state";
import { KnowledgeCard, type KnowledgeCardItem } from "../components/knowledge/knowledge-card";
import { frontendText, type LocaleRuntime } from "../lib/i18n";
import type { FavoriteKnowledgeItem, RecentKnowledgeItem, RecentResearchItem } from "../lib/knowledge-data";
import type { PrivateKnowledgeNoteListItem } from "../lib/knowledge-note";
import type { WorkspaceActivityItem } from "../lib/activity-data";
import type { ReviewItem, ReviewPeriod } from "../lib/review-data";

export type KnowledgeState = { kind: "loading" } | { kind: "ready"; items: readonly KnowledgeCardItem[]; nextCursor: string | null; pending?: boolean } | { kind: "error"; message: string };

export function KnowledgePage({ state, onLoadMore, locale, recent = [], favorites = [], recentResearch = [], notes = [], activity = [], activityNextCursor = null, onLoadMoreActivity, review, reviewPeriod = "daily", onReviewPeriodChange }: { state: KnowledgeState; onLoadMore?: () => void; locale?: LocaleRuntime; recent?: readonly RecentKnowledgeItem[]; favorites?: readonly FavoriteKnowledgeItem[]; recentResearch?: readonly RecentResearchItem[]; notes?: readonly PrivateKnowledgeNoteListItem[]; activity?: readonly WorkspaceActivityItem[]; activityNextCursor?: string | null; onLoadMoreActivity?: () => void; review?: { kind: "loading" } | { kind: "ready"; data: { items: readonly ReviewItem[] } } | { kind: "error" }; reviewPeriod?: ReviewPeriod; onReviewPeriodChange?: (period: ReviewPeriod) => void }) {
  if (state.kind === "loading") return <PageState kind="loading" title={frontendText(locale, "APP_LOADING_TITLE")} />;
  if (state.kind === "error") return <PageState kind="error" title={state.message || frontendText(locale, "KNOWLEDGE_ERROR")} />;
  return <section className="space-y-6"><div><h1 className="text-2xl font-semibold">{frontendText(locale, "KNOWLEDGE_TITLE")}</h1><p className="mt-1 text-sm text-muted-foreground">{frontendText(locale, "KNOWLEDGE_DESCRIPTION")}</p></div>{review && <ReviewPanel locale={locale} state={review} period={reviewPeriod} onPeriodChange={onReviewPeriodChange} />}{favorites.length > 0 && <ToReadPanel locale={locale} items={favorites} />}{recent.length > 0 && <RecentKnowledgePanel locale={locale} items={recent} />}{recentResearch.length > 0 && <RecentResearchPanel locale={locale} items={recentResearch} />}{notes.length > 0 && <PrivateNotesPanel locale={locale} notes={notes} />}{activity.length > 0 && <ActivityPanel locale={locale} items={activity} nextCursor={activityNextCursor} onLoadMore={onLoadMoreActivity} />}{state.items.length ? <div className="grid gap-4 md:grid-cols-2">{state.items.map((item) => <KnowledgeCard key={item.id} locale={locale} item={item} />)}</div> : <PageState kind="empty" title={frontendText(locale, "KNOWLEDGE_EMPTY")} />}{state.nextCursor && <Button variant="outline" disabled={state.pending} onClick={onLoadMore}>{frontendText(locale, "KNOWLEDGE_LOAD_MORE")}</Button>}</section>;
}

function ToReadPanel({ locale, items }: { locale?: LocaleRuntime; items: readonly FavoriteKnowledgeItem[] }) {
  return <Card data-to-read="true"><CardContent className="p-4"><div><h2 className="text-sm font-semibold">{frontendText(locale, "KNOWLEDGE_TO_READ_TITLE")}</h2><p className="mt-1 text-xs text-muted-foreground">{frontendText(locale, "KNOWLEDGE_TO_READ_DESCRIPTION")}</p></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{items.map((item) => <a key={item.id} href={`/knowledge/${encodeURIComponent(item.id)}`} className="rounded-md border p-3 text-sm transition hover:bg-accent"><div className="flex items-start justify-between gap-2"><span className="font-medium">{item.title.trim() || frontendText(locale, "KNOWLEDGE_UNTITLED")}</span><span className="shrink-0 rounded-full bg-muted px-2 py-0.5 text-[0.7rem]">{frontendText(locale, item.completed ? "KNOWLEDGE_TO_READ_COMPLETE" : "KNOWLEDGE_TO_READ_PENDING")}</span></div>{!item.completed && <span className="mt-1 block text-xs text-muted-foreground">{frontendText(locale, "KNOWLEDGE_TO_READ_OPEN")}</span>}</a>)}</div></CardContent></Card>;
}

function ReviewPanel({ locale, state, period, onPeriodChange }: { locale?: LocaleRuntime; state: { kind: "loading" } | { kind: "ready"; data: { items: readonly ReviewItem[] } } | { kind: "error" }; period: ReviewPeriod; onPeriodChange?: (period: ReviewPeriod) => void }) {
  return <Card data-knowledge-review="true"><CardContent className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">{frontendText(locale, "KNOWLEDGE_REVIEW_TITLE")}</h2><p className="mt-1 text-xs text-muted-foreground">{frontendText(locale, "KNOWLEDGE_REVIEW_DESCRIPTION")}</p></div><label className="flex items-center gap-2 text-xs text-muted-foreground"><span className="sr-only">{frontendText(locale, "KNOWLEDGE_REVIEW_PERIOD")}</span><select className="h-8 rounded-md border bg-background px-2" value={period} onChange={(event) => onPeriodChange?.(event.target.value === "weekly" ? "weekly" : "daily")}><option value="daily">{frontendText(locale, "KNOWLEDGE_REVIEW_DAILY")}</option><option value="weekly">{frontendText(locale, "KNOWLEDGE_REVIEW_WEEKLY")}</option></select></label></div>{state.kind === "loading" && <p className="mt-4 text-sm text-muted-foreground">{frontendText(locale, "KNOWLEDGE_REVIEW_LOADING")}</p>}{state.kind === "error" && <p className="mt-4 text-sm text-destructive">{frontendText(locale, "KNOWLEDGE_REVIEW_ERROR")}</p>}{state.kind === "ready" && (state.data.items.length ? <div className="mt-4 grid gap-2 sm:grid-cols-2">{state.data.items.map((item) => <a key={item.knowledgeItemId} href={`/knowledge/${encodeURIComponent(item.knowledgeItemId)}`} className="rounded-md border p-3 text-sm transition hover:bg-accent"><div className="flex items-start justify-between gap-2"><span className="font-medium">{item.title}</span><span className="shrink-0 rounded-full bg-muted px-2 py-0.5 text-[0.7rem]">{frontendText(locale, item.reason === "to_read" ? "KNOWLEDGE_REVIEW_TO_READ" : "KNOWLEDGE_REVIEW_NEW")}</span></div><span className="mt-1 block text-xs text-muted-foreground">{item.favorite ? frontendText(locale, "KNOWLEDGE_REVIEW_FAVORITE") : frontendText(locale, "KNOWLEDGE_REVIEW_PUBLISHED")}</span></a>)}</div> : <p className="mt-4 text-sm text-muted-foreground">{frontendText(locale, "KNOWLEDGE_REVIEW_EMPTY")}</p>)}</CardContent></Card>;
}

function ActivityPanel({ locale, items, nextCursor, onLoadMore }: { locale?: LocaleRuntime; items: readonly WorkspaceActivityItem[]; nextCursor: string | null; onLoadMore?: () => void }) {
  return <Card data-workspace-activity="true"><CardContent className="p-4"><h2 className="text-sm font-semibold">{frontendText(locale, "KNOWLEDGE_ACTIVITY_TITLE")}</h2><div className="mt-3 space-y-2">{items.map((item) => <a key={item.id} href={item.resourceType === "knowledge" ? `/knowledge/${encodeURIComponent(item.resourceId)}` : "/my-submissions"} className="flex items-center justify-between gap-3 rounded-md border p-3 text-sm transition hover:bg-accent"><span>{frontendText(locale, `ACTIVITY_${item.action.replace(".", "_").toUpperCase()}`)}</span><time className="shrink-0 text-xs text-muted-foreground">{item.createdAt}</time></a>)}</div>{nextCursor && <Button className="mt-3" variant="outline" onClick={onLoadMore}>{frontendText(locale, "KNOWLEDGE_ACTIVITY_LOAD_MORE")}</Button>}</CardContent></Card>;
}

function RecentKnowledgePanel({ locale, items }: { locale?: LocaleRuntime; items: readonly RecentKnowledgeItem[] }) {
  return <Card data-recent-knowledge="true"><CardContent className="p-4"><h2 className="text-sm font-semibold">{frontendText(locale, "KNOWLEDGE_RECENT_TITLE")}</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{items.map((item) => <a key={item.id} href={`/knowledge/${encodeURIComponent(item.id)}`} className="rounded-md border p-3 text-sm transition hover:bg-accent"><span className="block font-medium">{item.title.trim() || frontendText(locale, "KNOWLEDGE_UNTITLED")}</span><span className="mt-1 block text-xs text-muted-foreground">{frontendText(locale, "KNOWLEDGE_RECENT_VISITS")} {item.visitCount}</span></a>)}</div></CardContent></Card>;
}

function RecentResearchPanel({ locale, items }: { locale?: LocaleRuntime; items: readonly RecentResearchItem[] }) {
  return <Card data-recent-research="true"><CardContent className="p-4"><h2 className="text-sm font-semibold">{frontendText(locale, "KNOWLEDGE_RESEARCH_RECENT_TITLE")}</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{items.map((item) => <article key={item.id} className="rounded-md border p-3 text-sm"><div className="flex items-start justify-between gap-3"><p className="font-medium">{item.goal}</p><span className="shrink-0 rounded-full bg-muted px-2 py-0.5 text-xs">{frontendText(locale, `RESEARCH_STATUS_${item.status.toUpperCase()}`)}</span></div><p className="mt-2 text-xs text-muted-foreground">{frontendText(locale, "KNOWLEDGE_RESEARCH_SOURCES")} {item.sourceScope.spaceIds.length + item.sourceScope.collectionIds.length + item.sourceScope.knowledgeItemIds.length}</p><p className="mt-1 text-xs text-muted-foreground">{frontendText(locale, "KNOWLEDGE_RESEARCH_PROGRESS")} {item.checkpoint.completedSubquestionIds.length}/{item.subquestions.length}</p><a className="mt-3 inline-flex text-xs font-medium text-primary hover:underline" href={`/knowledge/${encodeURIComponent(item.knowledgeItemId)}?researchRunId=${encodeURIComponent(item.id)}`}>{frontendText(locale, "KNOWLEDGE_RESEARCH_OPEN")}</a></article>)}</div></CardContent></Card>;
}

function PrivateNotesPanel({ locale, notes }: { locale?: LocaleRuntime; notes: readonly PrivateKnowledgeNoteListItem[] }) {
  return <Card data-private-notes="true"><CardContent className="p-4"><div className="flex items-center justify-between gap-3"><h2 className="text-sm font-semibold">{frontendText(locale, "KNOWLEDGE_NOTES_LIST_TITLE")}</h2><span className="rounded-full border px-2 py-0.5 text-xs text-muted-foreground">{frontendText(locale, "KNOWLEDGE_NOTE_PRIVATE")}</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{notes.map((note) => <a key={note.id} href={`/knowledge/${encodeURIComponent(note.knowledgeItemId)}`} className="rounded-md border p-3 text-sm transition hover:bg-accent"><div className="flex items-center justify-between gap-2"><span className="block font-medium">{note.title.trim() || frontendText(locale, "KNOWLEDGE_UNTITLED")}</span>{note.access === "shared" && <span className="rounded-full border px-2 py-0.5 text-[0.7rem] text-muted-foreground">{frontendText(locale, "KNOWLEDGE_NOTE_SHARED")}</span>}</div><span className="mt-1 block text-xs text-muted-foreground">{note.body.trim().slice(0, 140) || frontendText(locale, "KNOWLEDGE_NOTE_EMPTY")}</span></a>)}</div></CardContent></Card>;
}
