import { useEffect, useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { frontendText, type LocaleRuntime } from "../lib/i18n";
import { applyTheme, readTheme, type ThemeMode } from "../lib/theme";

export function SettingsPage({ locale, email, role }: { locale: LocaleRuntime; email: string; role: "admin" | "contributor" }) {
  const [theme, setTheme] = useState<ThemeMode>("system");
  useEffect(() => setTheme(readTheme(window.localStorage)), []);
  const chooseTheme = (mode: ThemeMode) => { setTheme(mode); applyTheme(mode, document, window.localStorage); };
  return <section className="mx-auto max-w-3xl space-y-6"><div><p className="text-sm font-medium text-primary">{frontendText(locale, "APP_BRAND_EYEBROW")}</p><h1 className="mt-2 text-2xl font-semibold">{frontendText(locale, "SETTINGS_TITLE")}</h1><p className="mt-1 text-sm text-muted-foreground">{frontendText(locale, "SETTINGS_DESCRIPTION")}</p></div><div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>{frontendText(locale, "SETTINGS_ACCOUNT")}</CardTitle><CardDescription>{frontendText(locale, "SETTINGS_ACCOUNT_DESCRIPTION")}</CardDescription></CardHeader><CardContent className="space-y-3"><div><p className="text-xs text-muted-foreground">{frontendText(locale, "SETTINGS_EMAIL")}</p><p className="mt-1 text-sm font-medium">{email || frontendText(locale, "COMMON_VALUE_UNAVAILABLE")}</p></div><div><p className="text-xs text-muted-foreground">{frontendText(locale, "SETTINGS_ROLE")}</p><p className="mt-1 text-sm font-medium">{role === "admin" ? frontendText(locale, "SHELL_ADMIN_ROLE") : frontendText(locale, "SHELL_MEMBER_ROLE")}</p></div></CardContent></Card><Card><CardHeader><CardTitle>{frontendText(locale, "SETTINGS_APPEARANCE")}</CardTitle><CardDescription>{frontendText(locale, "SETTINGS_APPEARANCE_DESCRIPTION")}</CardDescription></CardHeader><CardContent className="space-y-3"><div className="grid grid-cols-3 gap-2">{(["light", "dark", "system"] as ThemeMode[]).map((mode) => <Button key={mode} type="button" variant={theme === mode ? "default" : "outline"} size="sm" aria-pressed={theme === mode} onClick={() => chooseTheme(mode)}>{frontendText(locale, mode === "light" ? "SHELL_THEME_LIGHT" : mode === "dark" ? "SHELL_THEME_DARK" : "SHELL_THEME_SYSTEM")}</Button>)}</div></CardContent></Card></div><Card><CardHeader><CardTitle>{frontendText(locale, "SETTINGS_LANGUAGE")}</CardTitle><CardDescription>{frontendText(locale, "SETTINGS_LANGUAGE_DESCRIPTION")}</CardDescription></CardHeader><CardContent><label className="flex max-w-xs items-center gap-3 text-sm"><span className="sr-only">{frontendText(locale, "SHELL_LANGUAGE_LABEL")}</span><select className="h-9 w-full rounded-md border bg-background px-3" value={locale.locale} onChange={(event) => locale.setLocale(event.target.value)}><option value="zh-CN">{frontendText(locale, "SHELL_LANGUAGE_ZH_CN")}</option><option value="en">{frontendText(locale, "SHELL_LANGUAGE_EN")}</option></select></label></CardContent></Card></section>;
}
