import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {build} from 'esbuild';
let dir,createKnowledgeImport;
before(async()=>{dir=await mkdtemp(new URL('./.vm-import-',import.meta.url).pathname);await build({entryPoints:['frontend/features/environments/files/knowledge-import.ts'],outfile:dir+'/module.mjs',bundle:true,platform:'node',format:'esm'});({createKnowledgeImport}=await import(dir+'/module.mjs'));});
after(async()=>{if(dir)await rm(dir,{recursive:true,force:true});});
const confirmation={title:'Reviewed note',target:{requestedSpaceId:'team-notes',requestedCollectionId:null,requestedVisibility:'admin_only'},acknowledged:true};
function fixture(t,{text='hello',requester,read}={}){let snapshot={status:'running',environmentId:'env-a'};const listeners=new Set(),calls=[],requests=[];const runtime={getSnapshot:()=>snapshot,subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);},async file(input){calls.push(input);return read?read(input):{text,version:'v1'};}};const model=createKnowledgeImport({runtime,requester:async(url,init)=>{requests.push({url,init});return requester?requester(url,init):Response.json({submission:{id:'submission-1',status:'pending'}});}});t.after(()=>model.dispose());return {model,calls,requests,switch(){snapshot={status:'closed',environmentId:null};for(const f of listeners)f();}};}
test('selected snapshot stays local until explicit consent and preserves requested destination',async t=>{const f=fixture(t);await f.model.select('/note.md');assert.equal(f.model.getSnapshot().kind,'preview');assert.equal(f.requests.length,0);await f.model.confirm({...confirmation,acknowledged:false});assert.equal(f.requests.length,0);await f.model.confirm(confirmation);assert.equal(f.requests.length,1);const {url,init}=f.requests[0];assert.equal(url,'/api/submissions');assert.equal(init.credentials,'same-origin');assert.deepEqual(JSON.parse(init.body),{requestedSpaceId:'team-notes',requestedCollectionId:null,requestedVisibility:'admin_only',kind:'markdown',title:'Reviewed note',content:'hello'});assert.match(init.headers['idempotency-key'],/^[A-Za-z0-9_-]{16,128}$/);assert.equal(f.model.getSnapshot().receipt.id,'submission-1');await f.model.confirm(confirmation);assert.equal(f.requests.length,1);});
test('unknown outcome locks original key, content and destination; only explicit retry sends',async t=>{let first=true;const f=fixture(t,{requester:()=>{if(first){first=false;throw Error('network');}return Response.json({submission:{id:'submission-1'}});}});await f.model.select('/note.txt');await f.model.confirm(confirmation);assert.equal(f.model.getSnapshot().kind,'unknown');f.model.close();await f.model.select('/different.txt');await f.model.confirm({...confirmation,title:'changed'});assert.equal(f.calls.length,1);assert.equal(f.requests.length,1);await f.model.retry();assert.equal(f.requests.length,2);assert.equal(f.requests[0].init.body,f.requests[1].init.body);assert.equal(f.requests[0].init.headers['idempotency-key'],f.requests[1].init.headers['idempotency-key']);assert.equal(f.model.getSnapshot().kind,'submitted');});
test('hidden paths, traversal, credential names and asset formats never reach file RPC',async t=>{for(const path of ['/.env','/a/.ssh/key.txt','/../a.txt','/a//b.txt','/credentials.json','/private-key.pem','/id_rsa','/report.pdf','/image.png','/file.constructor']){const f=fixture(t);await f.model.select(path);assert.equal(f.model.getSnapshot().kind,'error',path);assert.equal(f.calls.length,0,path);assert.equal(f.requests.length,0,path);}});
test('byte bounds, binary content and private keys are rejected before submission',async t=>{for(const text of ['', '中'.repeat(43691),'x\0y','-----BEGIN OPENSSH PRIVATE KEY-----\nAAA']){const f=fixture(t,{text});await f.model.select('/note.txt');assert.equal(f.model.getSnapshot().kind,'error');await f.model.confirm(confirmation);assert.equal(f.requests.length,0);}});
test('boundary text and malicious markup stay literal in the immutable snapshot',async t=>{const f=fixture(t,{text:'<script>alert(1)</script>'});await f.model.select('/note.html');assert.equal(f.model.getSnapshot().preview.draft.content,'<script>alert(1)</script>');assert.equal(f.model.getSnapshot().preview.draft.mode,'code');assert.equal(Object.isFrozen(f.model.getSnapshot().preview.draft),true);const g=fixture(t,{text:'a'.repeat(131072)});await g.model.select('/note.txt');assert.equal(g.model.getSnapshot().kind,'preview');});
test('runtime invalidation drops a late selected file and prevents submission',async t=>{let resolve;const f=fixture(t,{read:()=>new Promise(r=>resolve=r)});const task=f.model.select('/note.txt');f.switch();resolve({text:'secret old owner',version:'v1'});await task;assert.equal(f.model.getSnapshot().preview,undefined);await f.model.confirm(confirmation);assert.equal(f.requests.length,0);});
test('runtime invalidation aborts pending POST and ignores late receipt',async t=>{let resolve;const f=fixture(t,{requester:()=>new Promise(r=>resolve=r)});await f.model.select('/note.txt');const task=f.model.confirm(confirmation);f.switch();assert.equal(f.requests[0].init.signal.aborted,true);resolve(Response.json({submission:{id:'late'}}));await task;assert.equal(f.model.getSnapshot().kind,'idle');assert.equal(f.model.getSnapshot().receipt,undefined);await f.model.retry();assert.equal(f.requests.length,1);});
test('invalid destination and oversized title cannot send and preview can be corrected',async t=>{const f=fixture(t);await f.model.select('/a.txt');await f.model.confirm({...confirmation,title:'x'.repeat(201)});await f.model.confirm({...confirmation,target:{...confirmation.target,requestedSpaceId:''}});assert.equal(f.requests.length,0);assert.equal(f.model.getSnapshot().kind,'preview');await f.model.confirm(confirmation);assert.equal(f.model.getSnapshot().kind,'submitted');});
test('malformed success and server permission denial never become successful submissions',async t=>{for(const response of [()=>Response.json({submission:{id:''}}),()=>Response.json({error:{code:'FORBIDDEN',message:'Denied',retryable:false}},{status:403})]){const f=fixture(t,{requester:response});await f.model.select('/a.txt');await f.model.confirm(confirmation);assert.equal(f.model.getSnapshot().kind,'unknown');assert.equal(f.model.getSnapshot().receipt,undefined);assert.equal(f.requests.length,1);}});
