import { AppError } from "../http";

export const TERMINAL_ASSET_PARSE_CODES = new Set([
  "ASSET_PARSER_UNSUPPORTED", "ASSET_CONTENT_INVALID", "SOURCE_EMPTY", "SOURCE_TOO_LARGE", "SOURCE_METADATA_INVALID",
  "ASSET_AI_PARSE_UNSUPPORTED", "ASSET_AI_INPUT_TOO_LARGE", "ASSET_AI_OUTPUT_TOO_LARGE", "ASSET_IMAGE_PARSE_UNSUPPORTED", "ASSET_IMAGE_INPUT_TOO_LARGE", "ASSET_IMAGE_OUTPUT_TOO_LARGE",
  "ASSET_PDF_TOO_LARGE", "ASSET_PDF_PARSE_UNSUPPORTED", "ASSET_DOCX_TOO_LARGE", "ASSET_DOCX_PARSE_UNSUPPORTED", "ASSET_DOCX_EMPTY",
  "ASSET_XLSX_TOO_LARGE", "ASSET_XLSX_PARSE_UNSUPPORTED", "ASSET_XLSX_EMPTY", "ASSET_CSV_TOO_LARGE", "ASSET_CSV_PARSE_UNSUPPORTED", "ASSET_CSV_EMPTY",
  "ASSET_HTML_TOO_LARGE", "ASSET_HTML_OUTPUT_TOO_LARGE", "ASSET_HTML_EMPTY", "ASSET_XML_TOO_LARGE", "ASSET_XML_OUTPUT_TOO_LARGE", "ASSET_XML_EMPTY", "ASSET_XML_PARSE_UNSUPPORTED",
  "ASSET_ODF_TOO_LARGE", "ASSET_ODF_OUTPUT_TOO_LARGE", "ASSET_ODF_EMPTY", "ASSET_ODF_PARSE_UNSUPPORTED", "ASSET_NUMBERS_PARSE_UNSUPPORTED",
  "ASSET_PPTX_TOO_LARGE", "ASSET_PPTX_OUTPUT_TOO_LARGE", "ASSET_PPTX_EMPTY", "ASSET_PPTX_PARSE_UNSUPPORTED",
]);
const RETRYABLE_ASSET_PARSE_CODES = new Set(["ASSET_AI_PARSE_FAILED", "ASSET_ORIGINAL_MISSING", "ASSET_PARSE_RETRYABLE"]);

export interface AssetParseFailure { code: string; terminal: boolean }

/** Converts arbitrary parser/provider failures into a stable, content-free task error. */
export function classifyAssetParseFailure(error: unknown): AssetParseFailure {
  if (!(error instanceof AppError) || typeof error.code !== "string") return { code: "ASSET_PARSE_RETRYABLE", terminal: false };
  if (RETRYABLE_ASSET_PARSE_CODES.has(error.code)) return { code: error.code, terminal: false };
  if (!TERMINAL_ASSET_PARSE_CODES.has(error.code)) return { code: "ASSET_PARSE_RETRYABLE", terminal: false };
  return { code: error.code, terminal: true };
}
