export const UI = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Memory Garden</title><style>
:root{color-scheme:dark;--bg:#101512;--card:#19221c;--line:#304237;--ink:#eef7ef;--muted:#9eb3a4;--accent:#a7f070}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#25402d 0,transparent 38%),var(--bg);color:var(--ink);font:15px/1.55 ui-sans-serif,system-ui}main{max-width:1120px;margin:auto;padding:38px 22px}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:24px}h1{font:700 clamp(30px,6vw,58px)/1 Georgia,serif;margin:0}small,.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:370px 1fr;gap:18px}.card{background:color-mix(in srgb,var(--card) 94%,transparent);border:1px solid var(--line);border-radius:18px;padding:18px;box-shadow:0 16px 50px #0004}input,textarea,button{font:inherit}input,textarea{width:100%;color:var(--ink);background:#0e1510;border:1px solid var(--line);border-radius:10px;padding:11px;margin:5px 0 10px}textarea{min-height:170px;resize:vertical}button{border:0;border-radius:999px;padding:10px 16px;background:var(--accent);color:#13200f;font-weight:700;cursor:pointer}button.secondary{background:#29382e;color:var(--ink)}#results{display:grid;gap:9px;margin-top:12px}.hit{padding:12px;border:1px solid var(--line);border-radius:12px;cursor:pointer}.hit:hover{border-color:var(--accent)}#answer{white-space:pre-wrap;font-size:16px}.sources{margin-top:18px}.tag{display:inline-block;padding:2px 8px;background:#2c3d31;border-radius:99px;margin-right:5px;font-size:12px}@media(max-width:760px){.grid{grid-template-columns:1fr}header{align-items:start;flex-direction:column;gap:10px}}
</style></head><body><main><header><div><small>YOUR PRIVATE KNOWLEDGE AGENT</small><h1>Memory Garden</h1></div><button class="secondary" onclick="setToken()">设置令牌</button></header>
<div class="grid"><section class="card"><h2>写入知识</h2><input id="title" placeholder="标题"><input id="tags" placeholder="标签，用逗号分隔"><textarea id="content" placeholder="粘贴 Markdown、想法或资料…"></textarea><button onclick="saveNote()">保存笔记</button><p id="saveStatus" class="muted"></p><hr style="border-color:var(--line);border-width:1px 0 0;margin:22px 0"><h2>搜索</h2><input id="search" placeholder="关键词" onkeydown="event.key==='Enter'&&search()"><button class="secondary" onclick="search()">检索</button><div id="results"></div></section>
<section class="card"><h2>向知识库提问</h2><textarea id="question" style="min-height:95px" placeholder="例如：根据我的笔记，下周最重要的三件事是什么？"></textarea><button onclick="ask()">询问 Agent</button><p id="answer" class="muted">回答会严格引用你的笔记；知识库中没有依据时会明确说明。</p><div id="sources" class="sources"></div></section></div></main>
<script>
const token=()=>localStorage.getItem('memory-token')||''; const headers=()=>({'content-type':'application/json','authorization':'Bearer '+token()});
function setToken(){const v=prompt('APP_TOKEN（未配置服务端令牌时可留空）',token());if(v!==null)localStorage.setItem('memory-token',v)}
async function api(path,options={}){const r=await fetch(path,{...options,headers:{...headers(),...(options.headers||{})}});const data=await r.json().catch(()=>({error:r.statusText}));if(!r.ok)throw Error(data.error||r.statusText);return data}
async function saveNote(){try{const data=await api('/api/notes',{method:'POST',body:JSON.stringify({title:title.value,tags:tags.value.split(',').map(x=>x.trim()).filter(Boolean),content:content.value})});saveStatus.textContent='已保存：'+data.note.title;content.value=''}catch(e){saveStatus.textContent=e.message}}
function drawHits(hits,target=results){target.innerHTML=hits.map(h=>'<div class="hit"><b>'+esc(h.title)+'</b><p>'+esc(h.excerpt)+'</p>'+h.tags.map(t=>'<span class="tag">'+esc(t)+'</span>').join('')+'</div>').join('')||'<p class="muted">没有结果</p>'}
async function search(){try{drawHits((await api('/api/search?q='+encodeURIComponent(document.getElementById('search').value))).hits)}catch(e){results.textContent=e.message}}
async function ask(){answer.className='muted';answer.textContent='正在阅读知识库…';sources.innerHTML='';try{const d=await api('/api/chat',{method:'POST',body:JSON.stringify({question:question.value})});answer.className='';answer.textContent=d.answer;drawHits(d.sources,sources)}catch(e){answer.textContent=e.message}}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
</script></body></html>`;
