import { apiFetch, type Fetcher } from "./api";
import { createAsyncOwner } from "./async-owner";
import { assetPreviewModel, type AssetPreviewModel } from "../components/assets/asset-preview-model";
export interface AdminAsset { id: string; name?: string; status?: string; warnings?: string[]; }
export async function loadAdminAssets({ requester = fetch, signal }: { requester?: Fetcher; signal?: AbortSignal } = {}): Promise<AdminAsset[]> { const data = await apiFetch<{ items?: unknown[] }>("/api/admin/assets?limit=50", { requester, signal }); return Array.isArray(data.items) ? data.items.map(normalize).filter((item): item is AdminAsset => item !== null) : []; }
export async function retryAdminAsset(id: string, requester: Fetcher = fetch): Promise<void> { await apiFetch(`/api/admin/assets/${encodeURIComponent(id)}/retry`, { requester, method: "POST" }); }
export async function loadAdminAssetPreview(id: string, requester: Fetcher = fetch, signal?: AbortSignal): Promise<AssetPreviewModel> { const data = await apiFetch<unknown>(`/api/admin/assets/${encodeURIComponent(id)}/preview`, { requester, signal }); const preview = assetPreviewModel(data); if (!preview) throw new Error("ASSET_PREVIEW_INVALID"); return preview; }
function normalize(value: unknown): AdminAsset | null { if (!value || typeof value !== "object" || Array.isArray(value)) return null; const record = value as Record<string, unknown>; const asset = record.asset; const job = record.job; if (!asset || typeof asset !== "object" || !job || typeof job !== "object") return null; const a = asset as Record<string, unknown>; const j = job as Record<string, unknown>; if (typeof a.id !== "string" || !a.id) return null; return { id: a.id, name: typeof a.originalName === "string" ? a.originalName : undefined, status: typeof j.status === "string" ? j.status : undefined, warnings: [] }; }
export function createAdminAssetsRequestController(requester: Fetcher = fetch) { let active: AbortController | null = null; const owner = createAsyncOwner(); return { request() { active?.abort(); active = new AbortController(); const generation = owner.claim(); const promise = loadAdminAssets({ requester, signal: active.signal }).then((items) => ({ generation, items })); return { generation, promise }; }, isCurrent(generation: number) { return owner.isCurrent(generation); }, cancel() { owner.invalidate(); active?.abort(); active = null; } }; }
